### ISSUE TITLE
Please publish for Scala 2.10.0-RC2 and Akka 2.1.0-RC2. :-)

### ISSUE THREAD

**Issue by ghost** [sstone/akka-amqp-proxies#8]
Thanks!

**Comment by sstone** [comment]
I'll have a look at it tomorrow. It should be fairly straightforward except for the JSON part (currently based on Jerkson), so I'll probably remove the JSON serializer.

**Comment by ghost** [comment]
That's great, thanks!

While I'm asking for things: would it be possible for you to make the Akka dependency take "provided" scope, the way http://spray.io does? We're using all of this in an OSGi context, so it's quite helpful to just be able to drop in the Akka bundles at deployment time.

Thanks again!

**Comment by pm47** [comment]
Hi paul, I am not familiar with osgi, but couldn't you use maven exclusions?

**Comment by ghost** [comment]
Worst-case, yes, but I think the "provided" scope solution is preferable: it expresses that there's a compile-time dependency on Akka, but recognizes that your deployment process may not involve your build tool. Besides that, we use sbt, not Maven, and while we can do the exclude dance there, too, it's a bit unwieldy, and besides, making the build process express the modularization better seems generally preferable.

**Comment by sstone** [comment]
Ok, in the case of Akka the "provided" scope sounds reasonable. I'll update amqp-client too

**Comment by ghost** [comment]
Thanks! The new version integrates perfectly into my build now. Now I just need to test it... :-)
